# Generated by Django 5.1 on 2024-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(upload_to='')),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('birthdate', models.DateField()),
                ('date_joined_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователь',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
